'use strict';

// Do this as the first thing so that any code reading it knows the right env.
process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';

// Makes the script crash on unhandled rejections instead of silently
// ignoring them. In the future, promise rejections that are not handled will
// terminate the Node.js process with a non-zero exit code.
process.on('unhandledRejection', err => {
  throw err;
});

// Ensure environment variables are read.
require('../config/env');

const fs = require('fs');
const chalk = require('react-dev-utils/chalk');
const rspack = require('@rspack/core');
const { RspackDevServer } = require('@rspack/dev-server');
const clearConsole = require('react-dev-utils/clearConsole');
const checkRequiredFiles = require('react-dev-utils/checkRequiredFiles');
const {
  choosePort,
  createCompiler,
  prepareProxy,
  prepareUrls,
} = require('react-dev-utils/WebpackDevServerUtils');
const openBrowser = require('react-dev-utils/openBrowser');
const semver = require('semver');
const paths = require('../config/paths');
const configFactory = require('../config/webpack.config');
const createDevServerConfig = require('../config/webpackDevServer.config');
const getClientEnvironment = require('../config/env');
const react = require(require.resolve('react', { paths: [paths.appPath] }));

/** 脚本进程启动时刻（含读配置 / 选端口之前） */
const SCRIPT_STARTED_AT = Date.now();

function formatDuration(ms) {
  if (ms == null || Number.isNaN(ms)) {
    return 'n/a';
  }
  if (ms < 1000) {
    return `${ms}ms`;
  }
  return `${(ms / 1000).toFixed(2)}s`;
}

function printTiming(label, ms) {
  console.log(
    chalk.cyan(`[timing] ${label}: `) + chalk.bold(formatDuration(ms))
  );
}

const env = getClientEnvironment(paths.publicUrlOrPath.slice(0, -1));
const useYarn = fs.existsSync(paths.yarnLockFile);
const isInteractive = process.stdout.isTTY;

// Warn and crash if required files are missing
if (!checkRequiredFiles([paths.appHtml, paths.appIndexJs])) {
  process.exit(1);
}

const config = configFactory('development');

// Tools like Cloud9 rely on this.
const DEFAULT_PORT = config.devServer.port || parseInt(process.env.PORT, 10) || 3000;
const HOST = config.devServer.host || process.env.HOST || '0.0.0.0';

if (process.env.HOST) {
  console.log(
    chalk.cyan(
      `Attempting to bind to HOST environment variable: ${chalk.yellow(
        chalk.bold(process.env.HOST)
      )}`
    )
  );
  console.log(
    `If this was unintentional, check that you haven't mistakenly set it in your shell.`
  );
  console.log(
    `Learn more here: ${chalk.yellow('https://cra.link/advanced-config')}`
  );
  console.log();
}

// We require that you explicitly set browsers and do not fall back to
// browserslist defaults.
const { checkBrowsers } = require('react-dev-utils/browsersHelper');
checkBrowsers(paths.appPath, isInteractive)
  .then(() => {
    // We attempt to use the default port but if it is busy, we offer the user to
    // run on a different port. `choosePort()` Promise resolves to the next free port.
    return choosePort(HOST, DEFAULT_PORT);
  })
  .then(port => {
    if (port == null) {
      // We have not found a port.
      return;
    }

    const protocol = process.env.HTTPS === 'true' ? 'https' : 'http';
    const appName = require(paths.appPackageJson).name;

    const useTypeScript = fs.existsSync(paths.appTsConfig);
    const urls = prepareUrls(
      protocol,
      HOST,
      port,
      paths.publicUrlOrPath.slice(0, -1)
    );
    // Create a rspack compiler that is configured with custom messages.
    const compiler = createCompiler({
      appName,
      config,
      urls,
      useYarn,
      useTypeScript,
      webpack: rspack,
    });

    let isFirstCompile = true;
    let serverReadyAt = null;
    compiler.hooks.done.tap('GMDevTiming', (stats) => {
      const compileMs =
        stats.endTime != null && stats.startTime != null
          ? stats.endTime - stats.startTime
          : null;

      if (isFirstCompile) {
        printTiming('首次编译(Rspack compile)', compileMs);
        printTiming(
          '冷启动合计(yarn start → 首次编译完成)',
          Date.now() - SCRIPT_STARTED_AT
        );
        if (serverReadyAt != null) {
          printTiming(
            '其中 DevServer 监听就绪',
            serverReadyAt - SCRIPT_STARTED_AT
          );
        }
        isFirstCompile = false;
      } else {
        printTiming('增量编译(Rspack compile)', compileMs);
      }
    });

    const proxySetting = require(paths.appPackageJson).proxy;
    const proxyConfig = prepareProxy(
      proxySetting,
      paths.appPublic,
      paths.publicUrlOrPath
    );
    // Serve rspack assets generated by the compiler over a web server.
    const serverConfig = {
      ...createDevServerConfig(proxyConfig, urls.lanUrlForConfig),
      ...config.devServer,
      host: HOST,
      port,
    };
    const devServer = new RspackDevServer(serverConfig, compiler);
    // Launch RspackDevServer.
    devServer.startCallback(() => {
      serverReadyAt = Date.now();
      if (isInteractive) {
        clearConsole();
      }

      if (env.raw.FAST_REFRESH && semver.lt(react.version, '16.10.0')) {
        console.log(
          chalk.yellow(
            `Fast Refresh requires React 16.10 or higher. You are using React ${react.version}.`
          )
        );
      }

      // 注意：首次编译完成时 createCompiler 会 clearConsole，此处日志可能被清掉；
      // 完整耗时以 hooks.done 里的 [timing] 为准。
      console.log(chalk.cyan('Starting the development server...\n'));
      openBrowser(urls.localUrlForBrowser);
    });

    const stopDevServer = () => {
      // rspack-dev-server 1.x 用 stop；兼容旧 webpack-dev-server 的 close
      const stop =
        typeof devServer.stop === 'function'
          ? () => devServer.stop()
          : typeof devServer.close === 'function'
            ? () =>
                new Promise((resolve) => {
                  devServer.close(resolve)
                })
            : () => Promise.resolve()
      Promise.resolve(stop())
        .catch(() => {})
        .finally(() => {
          process.exit()
        })
    }

    ;['SIGINT', 'SIGTERM'].forEach(function (sig) {
      process.on(sig, stopDevServer)
    })

    if (process.env.CI !== 'true') {
      // Gracefully exit when stdin ends
      process.stdin.on('end', stopDevServer)
    }
  })
  .catch(err => {
    if (err && err.message) {
      console.log(err.message);
    }
    process.exit(1);
  });
